version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: maple_leafs_postgres
    restart: always
    environment:
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry
      POSTGRES_DB: telemetry_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: maple_leafs_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://telemetry:telemetry@postgres:5432/telemetry_db
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
  postgres_data:
    name: maple_leafs_hockey_telemetrics_db_data
